### ISSUE TITLE
Error when trying to save mock request file that doesn't exist

### ISSUE THREAD

**Issue by nogw** [woovibr/apiWithLog#10]
When executing the command "WRITE_MOCK=true yarn es scripts/test.ts", if the mock-requests.json file does not exist, an error message is displayed. However, the command also creates the file.

Error message:
```sh
> WRITE_MOCK=true yarn es scripts/test.ts

$ node -r esbuild-register -r node-fetch scripts/test.ts
{
  err: [Error: ENOENT: no such file or directory, open '/home/user/github/apiWithLog/mock-requests.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/user/github/apiWithLog/mock-requests.json'
  }
}
saved to /home/user/github/apiWithLog/mock-requests.json
```

**Comment by edumaciel10** [comment]
- [ ] create the file before try to access

**Comment by daniloab** [comment]
hi @nogw thanks for the issue.

May the solution here is to check if a mock JSON file exists when mock file env is true. Then, if not existing, it should create the file before trying to save it.

Can you complement your pull request with this try?
